### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by rodofshadows** [8HoLoN/Extension-HDS-Link-Detector#1]
First of, thank you for spending your time to make this! Much needed and appreciated.

I would suggest making it much easier to de/activate simply by clicking the icon or if that has a function I'm not aware of, right-click and have an option there.

Then I would suggest making the cmdline "empty" when no information about aHDS has been entered. What I mean by that, is send only the manifest link to the clipboard in that situation. I am making a batch downloader script for which I need easy access to the links. The script is using txt files for each batch and can batch those also.

Of cause I could change the script to use the full cmd your extension makes but that would take some of the other features I have made, away and I would really hate to delete good code..

PS. If there is a better way to communicate with you, please inform me. I know this does not qualify as a genuine issue, I just don't know how else to contact you.

**Comment by 8HoLoN** [comment]
Hello,

Thank you, I hope my work will be helpful for others by releasing it in free access. This way, everyone can feel free to donate whatever they want (or not) if they want to support this project.

With the version 0.0.2 it was possible to de/activate simply by clicking the icon. But with the arriving of the version 0.0.3, clicking the icon now open the UI. Therefore I will make a quick access button instead of the current checkbox under options tab.

OK, I understand the need to output only the manifest url into clipboard. It will be done very soon.
I suggest you could also put your script in github, it could interest people depending on the full purpose of your script.

For all the topics about this project, I prefer that it be centralized here, in issue section. For all other discussions that has no direct link with the project or that has no vocation to be public, you could contact me at : 8holon<at>gmail.com
I saw you just created an account in github to communicate. I understand that it's not quite as easy as sending an email and it could be an obstacle in the communication process.

**Comment by 8HoLoN** [comment]
All points were done with version 0.0.4.
